### ISSUE TITLE
DetailUpdate

### ISSUE THREAD

**Issue by LeeHannaa** [HGU-WALAB/ClassHub#132]
- [x] 모든 것(강의실에 대한 정보들, 강의실 이름, 강의실 설명, 교수이름, 입장코드 등등)을 이용해서 검색
- [x] 메인페이지 - 대시보드 삭제
- [x] 메인페이지 - 현재 강의실 입장 인원 공개
- [x] 구성원 정보 - email 수정 가능
- [x] 구성원 정보 - 구성원 삭제 가능

**Comment by 00KANGJK** [comment]
구성원 정보 email 수정 기능 추가
